apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hioaas-keyvault-dev
spec:
  provider: azure
  secretObjects:
  - secretName: liferay-tls
    type: kubernetes.io/tls
    data: 
    - objectName: aks-liferay-cert
      key: tls.key
    - objectName: aks-liferay-cert
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kv-hioaas-dev"
    objects: |
      array:
        - |
          objectName: aks-liferay-cert
          objectType: secret
          objectVersion: ""
    tenantId: "4c1af45f-b0de-403b-af7a-55034d442597"