/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hiop.hisc.servicecatalogs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Catalog service. Represents a row in the &quot;hisc_servicecatalog_Catalog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hiop.hisc.servicecatalogs.model.impl.CatalogModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hiop.hisc.servicecatalogs.model.impl.CatalogImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Catalog
 * @generated
 */
@ProviderType
public interface CatalogModel
	extends BaseModel<Catalog>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a catalog model instance should use the {@link Catalog} interface instead.
	 */

	/**
	 * Returns the primary key of this catalog.
	 *
	 * @return the primary key of this catalog
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this catalog.
	 *
	 * @param primaryKey the primary key of this catalog
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this catalog.
	 *
	 * @return the uuid of this catalog
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this catalog.
	 *
	 * @param uuid the uuid of this catalog
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the catalog ID of this catalog.
	 *
	 * @return the catalog ID of this catalog
	 */
	public long getCatalogId();

	/**
	 * Sets the catalog ID of this catalog.
	 *
	 * @param catalogId the catalog ID of this catalog
	 */
	public void setCatalogId(long catalogId);

	/**
	 * Returns the group ID of this catalog.
	 *
	 * @return the group ID of this catalog
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this catalog.
	 *
	 * @param groupId the group ID of this catalog
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this catalog.
	 *
	 * @return the company ID of this catalog
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this catalog.
	 *
	 * @param companyId the company ID of this catalog
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this catalog.
	 *
	 * @return the user ID of this catalog
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this catalog.
	 *
	 * @param userId the user ID of this catalog
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this catalog.
	 *
	 * @return the user uuid of this catalog
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this catalog.
	 *
	 * @param userUuid the user uuid of this catalog
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this catalog.
	 *
	 * @return the user name of this catalog
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this catalog.
	 *
	 * @param userName the user name of this catalog
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this catalog.
	 *
	 * @return the create date of this catalog
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this catalog.
	 *
	 * @param createDate the create date of this catalog
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this catalog.
	 *
	 * @return the modified date of this catalog
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this catalog.
	 *
	 * @param modifiedDate the modified date of this catalog
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category ID of this catalog.
	 *
	 * @return the category ID of this catalog
	 */
	@AutoEscape
	public String getCategoryId();

	/**
	 * Sets the category ID of this catalog.
	 *
	 * @param categoryId the category ID of this catalog
	 */
	public void setCategoryId(String categoryId);

	/**
	 * Returns the name of this catalog.
	 *
	 * @return the name of this catalog
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this catalog.
	 *
	 * @param name the name of this catalog
	 */
	public void setName(String name);

	@Override
	public Catalog cloneWithOriginalValues();

}