/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hiop.hisc.reports.model;

import com.hiop.hisc.reports.service.persistence.ReportPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Report service. Represents a row in the &quot;hisc_report_Report&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hiop.hisc.reports.model.impl.ReportModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hiop.hisc.reports.model.impl.ReportImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Report
 * @generated
 */
@ProviderType
public interface ReportModel
	extends BaseModel<Report>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a report model instance should use the {@link Report} interface instead.
	 */

	/**
	 * Returns the primary key of this report.
	 *
	 * @return the primary key of this report
	 */
	public ReportPK getPrimaryKey();

	/**
	 * Sets the primary key of this report.
	 *
	 * @param primaryKey the primary key of this report
	 */
	public void setPrimaryKey(ReportPK primaryKey);

	/**
	 * Returns the uuid of this report.
	 *
	 * @return the uuid of this report
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this report.
	 *
	 * @param uuid the uuid of this report
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the report ID of this report.
	 *
	 * @return the report ID of this report
	 */
	public long getReportId();

	/**
	 * Sets the report ID of this report.
	 *
	 * @param reportId the report ID of this report
	 */
	public void setReportId(long reportId);

	/**
	 * Returns the category ID of this report.
	 *
	 * @return the category ID of this report
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this report.
	 *
	 * @param categoryId the category ID of this report
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the group ID of this report.
	 *
	 * @return the group ID of this report
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this report.
	 *
	 * @param groupId the group ID of this report
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this report.
	 *
	 * @return the company ID of this report
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this report.
	 *
	 * @param companyId the company ID of this report
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this report.
	 *
	 * @return the user ID of this report
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this report.
	 *
	 * @param userId the user ID of this report
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this report.
	 *
	 * @return the user uuid of this report
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this report.
	 *
	 * @param userUuid the user uuid of this report
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this report.
	 *
	 * @return the create date of this report
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this report.
	 *
	 * @param createDate the create date of this report
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this report.
	 *
	 * @return the modified date of this report
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this report.
	 *
	 * @param modifiedDate the modified date of this report
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this report.
	 *
	 * @return the name of this report
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this report.
	 *
	 * @param name the name of this report
	 */
	public void setName(String name);

	/**
	 * Returns the description of this report.
	 *
	 * @return the description of this report
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this report.
	 *
	 * @param description the description of this report
	 */
	public void setDescription(String description);

	/**
	 * Returns the icon of this report.
	 *
	 * @return the icon of this report
	 */
	@AutoEscape
	public String getIcon();

	/**
	 * Sets the icon of this report.
	 *
	 * @param icon the icon of this report
	 */
	public void setIcon(String icon);

	/**
	 * Returns the sources of this report.
	 *
	 * @return the sources of this report
	 */
	@AutoEscape
	public String getSources();

	/**
	 * Sets the sources of this report.
	 *
	 * @param sources the sources of this report
	 */
	public void setSources(String sources);

	@Override
	public Report cloneWithOriginalValues();

}